name: gimme_goals
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  amplify_api: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  amplify_authenticator: ^1.4.3
  amplify_analytics_pinpoint: ^1.5.0
  amplify_datastore: ^1.5.0
  amplify_flutter: ^1.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  auto_route: 7.8.0
  injectable: ^2.1.2
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.1
  gap: ^3.0.1
  pinput: ^3.0.1
  flutter_easyloading: ^3.0.5
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.0
  injectable_generator: ^2.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
